spring.application.name=ai-semantic-schema-demo

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

spring.ai.google.genai.chat.temperature=0.1
spring.ai.google.genai.chat.max-output-tokens=500
spring.ai.google.genai.chat.top-p=0.95
spring.ai.google.genai.chat.top-k=2
spring.ai.google.genai.chat.stop-sequences=;
spring.ai.google.genai.chat.presence-penalty=0.0
spring.ai.google.genai.chat.frequency-penalty=0.0

logging.level.io.github.crystalplanetcode.aischema.timing=DEBUG